var files =
[
    [ "clock_management.c", "dc/d51/clock__management_8c.html", "dc/d51/clock__management_8c" ],
    [ "clock_management.h", "db/ddc/clock__management_8h.html", "db/ddc/clock__management_8h" ],
    [ "clock_management_test.c", "d9/d6b/clock__management__test_8c.html", "d9/d6b/clock__management__test_8c" ],
    [ "clock_management_test.h", "d3/df4/clock__management__test_8h.html", "d3/df4/clock__management__test_8h" ],
    [ "eeprom_test.c", "d7/d0b/eeprom__test_8c.html", "d7/d0b/eeprom__test_8c" ],
    [ "eeprom_test.h", "d3/d8f/eeprom__test_8h.html", "d3/d8f/eeprom__test_8h" ],
    [ "NPC_audio.c", "d2/dff/_n_p_c__audio_8c.html", "d2/dff/_n_p_c__audio_8c" ],
    [ "NPC_audio.h", "d5/d19/_n_p_c__audio_8h.html", "d5/d19/_n_p_c__audio_8h" ],
    [ "NPC_bluetooth.c", "de/d6e/_n_p_c__bluetooth_8c.html", "de/d6e/_n_p_c__bluetooth_8c" ],
    [ "NPC_bluetooth.h", "db/dfc/_n_p_c__bluetooth_8h.html", "db/dfc/_n_p_c__bluetooth_8h" ],
    [ "NPC_clock.c", "db/d0e/_n_p_c__clock_8c.html", "db/d0e/_n_p_c__clock_8c" ],
    [ "NPC_clock.h", "de/d02/_n_p_c__clock_8h.html", "de/d02/_n_p_c__clock_8h" ],
    [ "NPC_configuration.c", "d2/dfa/_n_p_c__configuration_8c.html", "d2/dfa/_n_p_c__configuration_8c" ],
    [ "NPC_configuration.h", "d2/d50/_n_p_c__configuration_8h.html", "d2/d50/_n_p_c__configuration_8h" ],
    [ "NPC_eeprom.c", "d4/dc0/_n_p_c__eeprom_8c.html", "d4/dc0/_n_p_c__eeprom_8c" ],
    [ "NPC_eeprom.h", "de/deb/_n_p_c__eeprom_8h.html", "de/deb/_n_p_c__eeprom_8h" ],
    [ "NPC_neopixel.c", "d5/d29/_n_p_c__neopixel_8c.html", "d5/d29/_n_p_c__neopixel_8c" ],
    [ "NPC_neopixel.h", "d4/dba/_n_p_c__neopixel_8h.html", "d4/dba/_n_p_c__neopixel_8h" ],
    [ "NPC_temperature.c", "d3/d0e/_n_p_c__temperature_8c.html", "d3/d0e/_n_p_c__temperature_8c" ],
    [ "NPC_temperature.h", "d8/d20/_n_p_c__temperature_8h.html", "d8/d20/_n_p_c__temperature_8h" ],
    [ "NPC_utils.c", "d6/d2d/_n_p_c__utils_8c.html", "d6/d2d/_n_p_c__utils_8c" ],
    [ "NPC_utils.h", "d7/da2/_n_p_c__utils_8h.html", "d7/da2/_n_p_c__utils_8h" ],
    [ "NPSC_nextion.c", "da/dae/_n_p_s_c__nextion_8c.html", "da/dae/_n_p_s_c__nextion_8c" ],
    [ "NPSC_nextion.h", "d1/dd6/_n_p_s_c__nextion_8h.html", "d1/dd6/_n_p_s_c__nextion_8h" ],
    [ "rtc_test.c", "de/d1a/rtc__test_8c.html", "de/d1a/rtc__test_8c" ],
    [ "rtc_test.h", "de/df2/rtc__test_8h.html", "de/df2/rtc__test_8h" ],
    [ "unitTest.c", "d7/d0b/unit_test_8c.html", "d7/d0b/unit_test_8c" ],
    [ "unitTest.h", "d0/da7/unit_test_8h.html", "d0/da7/unit_test_8h" ]
];