var searchData=
[
  ['configuration_20functions',['Configuration functions',['../group___audio___init.html',1,'']]],
  ['clock',['Clock',['../group___clock.html',1,'']]],
  ['clock_5fchoice',['CLOCK_Choice',['../group___c_l_o_c_k___choice.html',1,'']]],
  ['clock_5fcreatealarm',['clock_createAlarm',['../group___clock___alarms.html#ga5e1614dbb1a210106dbade3f133db27e',1,'NPC_clock.c']]],
  ['clock_5fformat',['CLOCK_Format',['../group___c_l_o_c_k___format.html',1,'']]],
  ['clock_5fgetdate',['clock_getDate',['../group___clock___time___date.html#gabb4d72928cb3d131d40067fb141003aa',1,'NPC_clock.c']]],
  ['clock_5fgettime',['clock_getTime',['../group___clock___time___date.html#ga03ae6948083c259f6edc0b146f40dc62',1,'NPC_clock.c']]],
  ['clock_5finit',['clock_init',['../group___clock___init.html#ga78ab77b57cf2e00089f0a3a22508524c',1,'NPC_clock.c']]],
  ['clock_5fmanagement',['Clock_Management',['../group___clock___management.html',1,'']]],
  ['clock_5fmanagement_2ec',['clock_management.c',['../clock__management_8c.html',1,'']]],
  ['clock_5fmanagement_2eh',['clock_management.h',['../clock__management_8h.html',1,'']]],
  ['clock_5fmanagement_5faddress',['Clock_management_address',['../group___clock__management__address.html',1,'']]],
  ['clock_5fmanagement_5falarm_5foffset',['Clock_management_alarm_offset',['../group___clock__management__alarm__offset.html',1,'']]],
  ['clock_5fmanagement_5falarmcomp',['Clock_Management_AlarmComp',['../group___clock___management___alarm_comp.html',1,'']]],
  ['clock_5fmanagement_5falarmupdate',['Clock_Management_AlarmUpdate',['../group___clock___management___alarm_update.html',1,'']]],
  ['clock_5fmanagement_5fconstants',['Clock_management_constants',['../group___clock__management__constants.html',1,'']]],
  ['clock_5fmanagement_5feeprom',['Clock_Management_Eeprom',['../group___clock___management___eeprom.html',1,'']]],
  ['clock_5fmanagement_5ftest',['Clock_management_test',['../group__clock__management__test.html',1,'']]],
  ['clock_5fmanagement_5ftest_2ec',['clock_management_test.c',['../clock__management__test_8c.html',1,'']]],
  ['clock_5fmanagement_5ftest_5fcomparison',['Clock_management_test_comparison',['../group__clock__management__test__comparison.html',1,'']]],
  ['clock_5fmanagement_5ftest_5fsave_5flod',['Clock_management_test_save_lod',['../group__clock__management__test__save__lod.html',1,'']]],
  ['clock_5fseta',['clock_setA',['../group___clock___alarms.html#gab56f512746d4f2638232db28bb7dac2b',1,'NPC_clock.c']]],
  ['clock_5fsetalarm',['clock_setAlarm',['../group___clock___alarms.html#gaea1a099c4ad6de8b99517ac6453e3569',1,'NPC_clock.c']]],
  ['clock_5fsetdate',['clock_setDate',['../group___clock___time___date.html#gaf16498fa2702bfda6b89a3335ccc7ca6',1,'NPC_clock.c']]],
  ['clock_5fsettime',['clock_setTime',['../group___clock___time___date.html#ga11404197d58ddf6b46230bcde4282ef2',1,'NPC_clock.c']]],
  ['clock_5fvalue',['CLOCK_Value',['../group___c_l_o_c_k___value.html',1,'']]],
  ['clockmanagement_5fisalarmbefore',['ClockManagement_isAlarmBefore',['../group___clock___management___alarm_comp.html#gaba2475baa28dfdc82e7a51a19fa8a7b9',1,'clock_management.c']]],
  ['clockmanagement_5fisdatebefore',['ClockManagement_isDateBefore',['../group___clock___management___alarm_comp.html#ga8e277f1ee687458304a10016dec2dbf7',1,'clock_management.c']]],
  ['clockmanagement_5fistimebefore',['ClockManagement_isTimeBefore',['../group___clock___management___alarm_comp.html#gaad24166797ca90cee706c0d8f4983560',1,'clock_management.c']]],
  ['clockmanagement_5floadalarm',['ClockManagement_loadAlarm',['../group___clock___management___eeprom.html#gab8401f24d519d3a2e54c3ba5dab80376',1,'clock_management.c']]],
  ['clockmanagement_5floaddate',['ClockManagement_loadDate',['../group___clock___management___eeprom.html#ga3980560a99803ef94287127ff3157f91',1,'clock_management.c']]],
  ['clockmanagement_5floadtime',['ClockManagement_loadTime',['../group___clock___management___eeprom.html#ga166e0bbb5e934cc45657ffad06ff1d62',1,'clock_management.c']]],
  ['clockmanagement_5fsavealarm',['ClockManagement_saveAlarm',['../group___clock___management___eeprom.html#ga98aa8b6a9e96cd5fd883602c23bf1c4a',1,'clock_management.c']]],
  ['clockmanagement_5fsavedate',['ClockManagement_saveDate',['../group___clock___management___eeprom.html#ga32f8e9df4e2b14dfa0db0300437fe335',1,'clock_management.c']]],
  ['clockmanagement_5fsavetime',['ClockManagement_saveTime',['../group___clock___management___eeprom.html#ga4d1c66f7ce4d69b6903471823ab105f7',1,'clock_management.c']]],
  ['clockmanagement_5fupdatealarm',['CLockManagement_updateAlarm',['../group___clock___management___alarm_update.html#gab3193e7c0f26b76a48829295caf4888f',1,'clock_management.c']]],
  ['configuration',['Configuration',['../group___configuration.html',1,'']]],
  ['constant',['Constant',['../group___constant.html',1,'']]],
  ['colour_20generation_20functions',['Colour generation functions',['../group___neo_pixel___colour.html',1,'']]],
  ['colour_20display_20functions',['colour display functions',['../group___neo_pixel___display.html',1,'']]]
];
